- hosts: all
  roles:
      - ansible-role-agent-devops
  vars:
    - az_devops_agent_role: build
    - az_devops_accountname: fmossamih	
    - az_devops_agent_username: faridagent3
    - az_devops_agent_user: farid2
    - az_devops_agent_pool_name: Ansible_Agent
    - az_devops_accesstoken: ************************
